apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec: 
  replicas: 2  
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:   
      labels:
        app: my-app
    spec:
      containers: 
      - name: static-site
        image: ghcr.io/nagarajutl/static-site:sha-bba1a14c53de01b143291099b1b1f30499ff5956

        ports:
        - containerPort: 80
        resources:   
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
##