apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: ClusterIP          # Changed from NodePort to ClusterIP
  ports:
    - port: 80
      targetPort: 80
      # Removed nodePort field here
  selector:
    app: my-app
