apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: ClusterIP  # or NodePort if you want external access
  ports:
    - port: 80           # service port (public in-cluster port)
      targetPort: 80     # match this with containerPort!
  selector:
    app: my-app
