apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: ClusterIP  # or NodePort if you want
  ports:
    - port: 80           # service port (can stay 80 if you want)
      targetPort: 8000   # container port your app is listening on
  selector:
    app: my-app
