name: ci/cd pipeline
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    name: Docker build and push
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
  update-k8s:
    name: update kubernetes Deployment file
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name : Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: setup git config
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "
      - name: update deployment.yaml
        run: |
          sed -i "s|image: my-image:latest|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" deployment.yaml
      - name: commit changes
        run: |
          git add deployment.yaml
          git commit -m "update image to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: push changes
        run: |
          git push origin main
  